services:

# Models
    model.task:
        class: Fintem\UserTaskBundle\Model\TaskModel
        arguments:
            - '@doctrine.orm.default_entity_manager'

# Param converters
    param_converter.task:
        class: Fintem\UserTaskBundle\ParamConverter\TaskParamConverter
        arguments:
            - '@model.task'
        tags:
            - { name: request.param_converter, priority: 0, converter: task }

# Twig extensions
    twig.extension.task:
        class: Fintem\UserTaskBundle\Twig\TaskExtension
        arguments:
            - '@model.task'
        tags:
            - { name: twig.extension }